env = Environment (CXX = 'ccache g++')
env = Environment (CC  = 'ccache gcc')

Program ('server',
        ['content/game.cpp',
         'content/courseitem.cpp',
         'content/LoginCheck.cpp',
         'content/course.cpp',
         'content/makehouse.cpp',
         'content/puzzle.cpp',
         'content/room.cpp',
         'content/roommanager.cpp',
         'content/student.cpp',
         'content/teacher.cpp',
         'content/DataTool.cpp',
         'handler/HandleBuildHouse.cpp',
         'handler/HandleCartoon.cpp',
         'handler/HandleClassRoom.cpp',
         'handler/HandleExercise.cpp',
         'handler/HandleMessage.cpp',
         'handler/HandlePuzzle.cpp',
         'handler/HandleRainbowValley.cpp',
         'handler/HandleSprite.cpp',
         'AuthTask.cpp',
         'Config.cpp',
         'database.cpp',
         'Evloop.cpp',
         'main.cpp',
         'memcached.cpp',
         'ProcessManager.cpp',
         'RecvTask.cpp',
         'SendTask.cpp',
         'Single.cpp',
         'ThreadPool.cpp',
         'Sock.c'],

        LIBS    = ['memcached','pthread','ev','glog','mysqlcppconn','lua5.2'],
        LIBPATH = ['/usr/lib','/usr/local/lib'],
        CCFLAGS = ['-Wall','-Werror','-g','-DDEBUG','-D_RBV_TEST','-D_BUILDHOUSE_LONGLONG'],
        CPPPATH = ['-I.','-I./includes','-I./handler','-I./content','-I./handler/task']
        )
